---
title: "Super Awesome Notebook"
output: html_notebook
---

Run ze pipeline
```{r}
fname <- '../data/discovery_metav3.0.meta'
dirty_df <- read.csv(file=fname, nrows=1000000, header=TRUE, sep=' ')
# dump stuff with missing p's
good_df <- dirty_df[!is.na(dirty_df$P),]
df <- good_df[good_df$P < 5e-8,]


```


Do we know the ld?
If so.. could we use to do this better?

```{r}

cut_df <- df
df$REGION = integer(nrow(df))

lead_snps <- data.frame()

reg = 1
while(min(cut_df$P) < 5e-8){
  
  lead_snp = cut_df[which.min(cut_df$P),]
  
  lims = c( max(0, lead_snp$BP - 5e5), lead_snp$BP + 5e5 )
  
  snps_in_region <- cut_df[ cut_df$BP > lims[1] & cut_df$BP < lims[2] & cut_df$CHR == as.numeric(lead_snp['CHR']), ] # check chr
  
  df$REGION[ (rownames(df) %in% rownames(snps_in_region) ) ] <- reg
  
  lead_snps <- rbind(lead_snps, lead_snp)
  
  cut_df <- cut_df[! (rownames(cut_df) %in% rownames(snps_in_region)),]
  
  reg <- reg + 1
  
  
}


```
Gonna need

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("biomaRt")


```{r}
# Gene stuff

require(biomaRt)
ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl",mart=ensembl)

```

```{r}
# Grab the genes

f <- function(lead_snp) {
  region_genes <- getBM(attributes=c('chromosome_name', 'start_position', 'end_position', 'strand', 'ensembl_gene_id'),
      filters=c('chromosome_name', 'start', 'end'),
      values=list(as.numeric(lead_snp['CHR']), as.numeric(lead_snp['BP']) - 5e5, as.numeric(lead_snp['BP']) + 5e5),
      mart=ensembl)
  region_genes$REGION = lead_snp['REGION']
  region_genes
}

genes <- do.call(rbind, apply(lead_snps, 1, f))

```


```{r}
xlim <- c(2470848, 2500000)
ylim <- c(0, 100)
par(xaxs='i',yaxs='i',mar=c(5,1,1,1));
px = sig_snps_df$BP
py = integer(nrow(sig_snps_df))
plot(px, py,xlim=xlim,ylim=ylim,ann=F);




```
